# Generated by Django 4.1 on 2022-11-26 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0002_forms_bio_delete_post"),
    ]

    operations = [
        migrations.AddField(
            model_name="forms_bio",
            name="closed",
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="forms_bio",
            name="type",
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
