# Generated by Django 4.1 on 2022-12-01 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0003_forms_bio_closed_forms_bio_type"),
    ]

    operations = [
        migrations.RenameField(
            model_name="forms_bio",
            old_name="closed",
            new_name="externo",
        ),
        migrations.RemoveField(
            model_name="forms_bio",
            name="type",
        ),
    ]
