# Generated by Django 4.1 on 2022-12-01 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0004_rename_closed_forms_bio_externo_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="forms_bio",
            name="closed",
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
